# argocd/projects/platform.yaml
# AppProject สำหรับ platform team — มีสิทธิ์เต็มใน cluster-scoped resources
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: "Shared platform services — Admin only"
  sourceRepos:
    - https://git.example.com/platform-gitops.git
  destinations:
    - namespace: "cert-manager"
      server: https://kubernetes.default.svc
    - namespace: "ingress-nginx"
      server: https://kubernetes.default.svc
    - namespace: "monitoring"
      server: https://kubernetes.default.svc
    - namespace: "devtron"
      server: https://kubernetes.default.svc
    - namespace: "argocd"
      server: https://kubernetes.default.svc
    - namespace: "kube-system"
      server: https://kubernetes.default.svc
  # Platform team ต้องการ cluster-scoped resources (CRD, ClusterRole, etc.)
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: admin
      description: Platform admin full access
      policies:
        - p, proj:platform:admin, applications, *, platform/*, allow
      groups:
        - platform-admins
